name: CICD

on: 
  workflow_dispatch:
    inputs:
       enviroment:
        description: this is the environment value where workflows runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
  
jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "clone code from github"
  
  build:
     runs-on: ubuntu-latest
     steps:
       - name: build docker container
         run: echo "docker container build"
   
  test:
     runs-on: ubuntu-latest
     steps:
      - name: test the container
        run: echo "container testing"
   
  deploye:
      if: inputs.environment == 'dev'
      runs-on: ubuntu-latest
      steps:
        - name: deploye app
          run: echo "docker compose deploying a app"


