name: CICD

on: 
  workflow_dispatch:
  
jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "clone code from github"
  
  build:
     runs-on: ubuntu-latest
     steps:
       - name: build docker container
         run: echo "docker container build"
   
  test:
     runs-on: ubuntu-latest
     steps:
      - name: test the container
        run: echo "container testing"
   
  deploye:
      runs-on: ubuntu-latest
      steps:
        - name: deploye app
          run: echo "docker compose deploying a app"


